# Generated by Django 5.1.1 on 2024-10-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_prettynum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prettynum',
            old_name='mobole',
            new_name='mobile',
        ),
    ]
